
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/course?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=uvcGjHGDxPykOFcBjtWlQYlFeuUCwcYb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

