#data base configuration
spring.profiles.active=${ENV:dev}







logging.level.org.springframework.security=DEBUG
spring.security.user.name=demo
spring.security.user.password=demo
spring.security.user.roles=ADMIN